# Generated by Django 2.0.5 on 2018-06-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('idProfesor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('asignatura', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor'),
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
