# Generated by Django 2.0.5 on 2018-06-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180602_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='clase',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomClase', models.CharField(max_length=30)),
                ('nHoras', models.IntegerField()),
                ('idProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='idPersona',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
