# Generated by Django 2.0.5 on 2018-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180607_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('idAlumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('carrera', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=40)),
            ],
        ),
    ]
